# docker-compose.yml

services:
  api-tests:
    build:
      context: .
    working_dir: /app
    volumes:
      - .:/app
    command: ["python", "-m", "pytest", "api_tests",
              "--html=reports/api-report.html", "--self-contained-html",
              "--cov=api_tests", "--cov-report=html"]

  web-smoke:
    build:
      context: .
    working_dir: /app/web_tests
    volumes:
      - .:/app
    command: ["npx", "playwright", "test", "-g", "@smoke", "--reporter=html"]

  web-regression:
    build:
      context: .
    working_dir: /app/web_tests
    volumes:
      - .:/app
    command: ["npx", "playwright", "test", "-g", "@regression", "--reporter=html"]

  grpc-mock:
    image: bavix/gripmock:latest
    command: ["--stub=/stubs", "/protos/health.proto"]
    ports:
      - "4770:4770"   # gRPC server
      - "4771:4771"   # admin/UI
    volumes:
      - ./protos:/protos:ro
      - ./protos/stubs:/stubs:ro

  prism:
    image: stoplight/prism:5
    command: ["mock", "-h", "0.0.0.0", "/spec/openapi.yaml"]
    ports:
      - "4010:4010"
    volumes:
      - ./api/spec:/spec:ro

