name: API Tests

on:
  push:
    paths:
      - "api_tests/**"
      - ".github/workflows/api-tests.yml"
  pull_request:
    paths:
      - "api_tests/**"
      - ".github/workflows/api-tests.yml"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  api:
    name: API (pytest)
    runs-on: ubuntu-latest

    env:
      API_BASE_URL: ${{ secrets.API_BASE_URL }} 
      API_TOKEN: ${{ secrets.API_TOKEN }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Cache pip
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('api_tests/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Ensure API_BASE_URL default
        run: echo "API_BASE_URL=${API_BASE_URL:-https://pokeapi.co/api/v2}" >> $GITHUB_ENV

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r api_tests/requirements.txt
          # Optional (if not already in requirements.txt):
          # pip install pytest-html pytest-cov pytest-xdist

      - name: Run pytest (parallel + coverage + junit + html)
        run: |
          mkdir -p test-results
          python -m pytest api_tests \
            -n auto \
            --durations=10 \
            --cov=api_tests \
            --cov-report=term-missing \
            --cov-report=xml \
            --cov-report=html \
            --junitxml=test-results/junit.xml \
            --html=test-results/api-report.html --self-contained-html

      - name: Upload HTML report & coverage
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: api-report-and-coverage
          path: |
            test-results/api-report.html
            htmlcov
            coverage.xml

      - name: Upload junit (failures only)
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: api-junit
          path: test-results/junit.xml

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4
        with:
          files: coverage.xml
          fail_ci_if_error: true
          token: ${{ secrets.CODECOV_TOKEN }} # only needed for private repos

      - name: Job summary
        if: always()
        run: |
          {
            echo "## API Tests"
            echo ""
            echo "- HTML report artifact: \`test-results/api-report.html\`"
            echo "- Coverage report artifact: \`htmlcov/\` (open \`index.html\`)"
            echo "- Coverage XML: \`coverage.xml\` (sent to Codecov)"
            echo "- Parallel: \`-n auto\` (ensure pytest-xdist installed)"
          } >> $GITHUB_STEP_SUMMARY

