name: API Tests

on:
  push:
  pull_request:

jobs:
  api:
    name: API (pytest)
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r api_tests/requirements.txt
          pip install pytest-html

      - name: Run pytest (coverage + junit + html)
        run: |
          mkdir -p test-results
          python -m pytest api_tests \
            --cov=api_tests \
            --cov-report=term-missing \
            --cov-report=xml \
            --cov-report=html \
            --junitxml=test-results/junit.xml \
            --html=test-results/api-report.html --self-contained-html

      - name: Upload API artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: api-report
          path: |
            test-results
            htmlcov
            coverage.xml

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4
        with:
          files: coverage.xml
          fail_ci_if_error: true
