# .github/workflows/deploy-reports.yml
name: Deploy Reports

on:
  workflow_run:
    workflows: ["Web Smoke Tests", "Web Regression Tests"]
    types: [completed]

permissions:
  contents: write   # allow committing to the repo

jobs:
  deploy:
    name: Commit Playwright reports to /docs on main
    runs-on: ubuntu-latest
    # publish even if tests failed (so you can see the report)
    if: ${{ github.event.workflow_run.conclusion == 'success' || github.event.workflow_run.conclusion == 'failure' }}

    steps:
      - name: Checkout main (full history)
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: main

      - name: Download smoke report (if present)
        uses: actions/download-artifact@v4
        with:
          name: web-smoke-report
          path: docs/web-smoke-report
          run-id: ${{ github.event.workflow_run.id }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
        continue-on-error: true

      - name: Download regression report (if present)
        uses: actions/download-artifact@v4
        with:
          name: web-regression-report
          path: docs/web-regression-report
          run-id: ${{ github.event.workflow_run.id }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
        continue-on-error: true

      - name: Ensure index.html exists
        run: |
            python - <<'PY'
            import os, textwrap

            os.makedirs("docs", exist_ok=True)
            path = "docs/index.html"

            if not os.path.exists(path):
                html = """\
                <!doctype html><meta charset="utf-8">
                <title>Playwright Reports</title>
                <link rel="preconnect" href="https://fonts.googleapis.com"><link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
                <link href="https://fonts.googleapis.com/css2?family=Inter:wght@400;600&display=swap" rel="stylesheet">
                <style>
                    body{font-family:Inter,system-ui,-apple-system,Segoe UI,Roboto,Arial,sans-serif;margin:2rem;line-height:1.6}
                    h1{margin-bottom:0.5rem}
                    .card{border:1px solid #e5e7eb;border-radius:12px;padding:1rem;margin:1rem 0}
                    a{color:#2563eb;text-decoration:none}
                    a:hover{text-decoration:underline}
                </style>
                <h1>Playwright Reports</h1>
                <p>Browse the latest published reports from CI.</p>
                <div class="card">
                    <h2>Smoke</h2>
                    <p><a href="web-smoke-report/index.html">Open smoke report</a></p>
                </div>
                <div class="card">
                    <h2>Regression</h2>
                    <p><a href="web-regression-report/index.html">Open regression report</a></p>
                </div>
                """
                with open(path, "w", encoding="utf-8") as f:
                        f.write(textwrap.dedent(html))
            PY



      - name: Commit and push changes
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add docs/
          git commit -m "Update Playwright reports [skip ci]" || echo "No changes"
          git push
