name: Deploy Reports

on:
  workflow_run:
    workflows: ["Web Smoke Tests", "Web Regression Tests"]
    types:
      - completed

jobs:
  deploy:
    name: Deploy latest Playwright report to GitHub Pages
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' || github.event.workflow_run.conclusion == 'failure' }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Download report artifact
        uses: actions/download-artifact@v4
        with:
          name: web-smoke-report
          path: docs/playwright-report
        continue-on-error: true

      - name: Download regression report artifact
        uses: actions/download-artifact@v4
        with:
          name: web-regression-report
          path: docs/playwright-report
        continue-on-error: true

      - name: Commit and push updated report
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add docs/
          git commit -m "Update Playwright report [skip ci]" || echo "No changes"
          git push
