# docker-compose.yml (Compose v2, no "version:", no "x-base")

    services:
    # -------------------- API --------------------
    api-tests:
    build:
      context: .
    container_name: qa-api-tests
    working_dir: /app
    volumes:
      - .:/app
    command: >
      python -m pytest api_tests
      --html=reports/api-report.html --self-contained-html
      --cov=api_tests --cov-report=html

  # -------------------- WEB (Playwright) --------------------
     web-smoke:
    build:
      context: .
    container_name: qa-web-smoke
    working_dir: /app/web_tests
    volumes:
      - .:/app
    command: >
      npx playwright test -g "@smoke" --reporter=html
    # If you use TS path aliases at runtime:
    # environment:
    #   NODE_OPTIONS: -r tsconfig-paths/register

    web-regression:
    build:
      context: .
    container_name: qa-web-regression
    working_dir: /app/web_tests
    volumes:
      - .:/app
    command: >
      npx playwright test -g "@regression" --reporter=html
    # environment:
    #   NODE_OPTIONS: -r tsconfig-paths/register
