name: Tests

on:
  push:
  pull_request:

jobs:
  # --- API TESTS JOB ---
  api:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - run: |
          python -m pip install --upgrade pip
          pip install -r api_tests/requirements.txt
          pytest api_tests --cov=api_tests --cov-report=term-missing

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r api_tests/requirements.txt

      - name: Run pytest (with coverage + JUnit)
        run: |
          mkdir -p test-results
          python -m pytest api_tests \
            --cov=api_tests \
            --cov-report=term-missing \
            --cov-report=xml \
            --cov-report=html \
            --junitxml=test-results/junit.xml

      # Node setup
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - run: |
          cd web-tests
          npm ci
          npx playwright install --with-deps
          npx playwright test

            

      - name: Upload JUnit & Coverage HTML
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: api-tests-artifacts
          path: |
            test-results
            htmlcov
            coverage.xml

  # --- WEB TESTS JOB (Playwright) ---
  e2e:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: web-tests
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install deps
        run: |
          npm ci
          npx playwright install --with-deps

      - name: Run tests
        run: npx playwright test

      - name: Upload Playwright report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: web-tests/playwright-report

      - name: Upload test-results (traces/videos/screenshots)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: web-test-results
          path: web-tests/test-results
