name: Web Regression Tests

on:
  pull_request:

    
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  web-regression:
    name: Regression (${{ matrix.browser }})
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        browser: [chromium, firefox, webkit]
    
    defaults:
      run:
        working-directory: web_tests

    env:
      USERNAME: ${{ secrets.E2E_USERNAME }}
      PASSWORD: ${{ secrets.E2E_PASSWORD }}
      BASE_URL: ${{ secrets.BASE_URL }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Cache npm
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: ${{ runner.os }}-npm-${{ hashFiles('web-tests/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-npm-

      - name: Install deps & browsers
        run: |
          npm ci
          npx playwright install --with-deps

      - name: Run regression tests (${{ matrix.browser }})
        run: npx playwright test -g "@regression" --reporter=html --project=${{ matrix.browser }}

      - name: Upload Playwright report (${{ matrix.browser }})
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: web-regression-report ${{ matrix.browser }}
          path: web_tests/playwright-report

      - name: Upload test results (${{ matrix.browser }})
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: web-regression-test-results-${{ matrix.browser }}
          path: web-tests/test-results

      - name: Upload traces/screenshots/videos
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: web-regression-test-results
          path: web_tests/test-results
